### ISSUE TITLE
Build error on RCTWebSocket

### ISSUE THREAD

**Issue by dbertella** [AlessioVecchi/RNRicetteApp#1]
I was trying to build the application on my computer but the build failed, I thought it was node version I had 5.0, but even with 4.0 I have problems, apparently different problem, but still I can't succeed.

Which version of node do you have there, and which version of IOS do you target as well?

Here a screenshot. Thanks! :-D
![screen shot 2015-11-05 at 08 37 03](https://cloud.githubusercontent.com/assets/2563196/10962452/845af6b8-8398-11e5-9e9c-c4d5480e3bdc.png)

**Comment by AlessioVecchi** [comment]
Hi Daniele,

which version of XCode are you using? 
I have the 7.1 installed-

bye
A

**Comment by dbertella** [comment]
I don't know how but it's working on my new mac :+1: I'll close the issue, and I'll send you pull requests instead :-D
